# Generated by Django 6.1.1 on 2026-09-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercreate',
            options={'ordering': ['name', 'birth_date']},
        ),
        migrations.AddField(
            model_name='usercreate',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
