[project]
name = "homework-12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RUMpumoriginal", email = "novykroman12@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=6.1.1",
]

[project.scripts]
homework-12 = "homework_12:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
